[project]
name = "aoc"
version = "1.0.0"
authors = [
    { name = "Yann Aguettaz" }
]
dependencies = [
    "requests"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only_include = ['aoc', 'secret']

